web:
  #image: dwoodard/ankor:php7_laravel
  build: ./docker/web/laravel/5.3
  container_name: ${CONTAINER_NAME}
  volumes:
  - .:/var/www/html
  links:
  - db:mysql
  ports:
  - 80:80
  - 443:443

db:
  image: mysql:5.6
  container_name: ${CONTAINER_NAME}
  environment:
     - MYSQL_ROOT_PASSWORD=root
  ports:
  - 3306:3306
  volumes:
  - ./data/mysql:/var/lib/mysql

phpmyadmin:
  image: corbinu/docker-phpmyadmin
  container_name: ${CONTAINER_NAME}
  links:
    - db:mysql
  ports:
    - 8181:80
  environment:
    MYSQL_USERNAME: root
    MYSQL_ROOT_PASSWORD: root

#queue:
#  image: beanstalkd
#  container_name: ${CONTAINER_NAME}
